---
- name: Auto-generate passwords
  expect:
    command: /usr/share/elasticsearch/bin/elasticsearch-reset-password -u elastic
    responses:
      '(.*)Please confirm that you would like to continue(.*)': 'y'
  register: auth
  ignore_errors: true
  changed_when: auth.rc == 0
  failed_when: auth.rc not in [0, 78]

- name: Generate password file
  copy:
    content: "{{ auth.stdout }}"
    dest: /tmp/passwords.txt
  when:
    - (auth.rc == 0) or (auth.rc == 78)

- name: Download password file
  fetch:
    src: /tmp/passwords.txt
    dest: "{{ output_artifacts_path }}/passwords.txt"
    flat: true
  when:
    - (auth.rc == 0) or (auth.rc == 78)

- name: Remove password file from server
  file:
    path: /tmp/passwords.txt
    state: absent